/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AbstractJsonSchemaPropertyObjectDto } from './abstractJsonSchemaPropertyObject';
import { ItemDto } from './item';


export interface JsonSchemaDto { 
    title?: string;
    description?: string;
    properties?: { [key: string]: AbstractJsonSchemaPropertyObjectDto; };
    requiredProperties?: Array<string>;
    definitions?: { [key: string]: ItemDto; };
    type?: string;
    $schema?: string;
}

